### ISSUE TITLE
Exception trying to load twitter credentials from .env

### ISSUE THREAD

**Issue by scotttam** [mondok/hshtg#1]
Hi Matt,

I created a .env file and added my twitter credentials. When I try to run, I get the following exception:

```
ruby hshtg.rb
/dev_exclusions/rpt-submissions/matt_mondok/hshtg/lib/hshtg/util/utils.rb:61:in `block in     load_env_vars': undefined method `[]' for nil:NilClass (NoMethodError)
from /dev_exclusions/rpt-submissions/matt_mondok/hshtg/lib/hshtg/util/utils.rb:59:in `each_line'
from /dev_exclusions/rpt-submissions/matt_mondok/hshtg/lib/hshtg/util/utils.rb:59:in `load_env_vars'
from hshtg.rb:7:in `<main>'
```

**Comment by mondok** [comment]
Thanks - looking into it now.

**Comment by mondok** [comment]
Sorry about that.  I wasn't handling non-env lines and provided a sample that the app couldn't parse to boot.  It should be fixed now.
